### ISSUE TITLE
[Bug] Missing RBAC Permissions for PersistentVolumeClaims for AWS "emr-containers" Service causing SparkDriver to not clean up PVC resources.

### ISSUE THREAD

**Issue by pthatchinamoorthy** [eksctl-io/eksctl#7410]
### What were you trying to accomplish?
Submit a `emr-6.12.0` Spark Job to an EKS cluster using AWS Service "emr-containers" 

### What happened?
The Job submitted to AWS Service "emr-containers" runs well, and  completed successfully. However, the Spark Driver while closing the SparkContext threw the error message 
```
User "system:serviceaccount:XXXXXXXXXX:emr-containers-sa-spark-driver-XXXXXXXXXX-XXXXXXXXXX" cannot deletecollection resource "persistentvolumeclaims" in API group "" in the namespace XXXXXXXXXX
```

### How to reproduce it?
Step 0: Perform all the prerequisites listed at https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up.html

Step 1: Setup the IamIdentityMapping for the Service "emr-containers" to use the EKS cluster namespace
```
% eksctl create iamidentitymapping --cluster <cluster_name> --namespace <namespace> --service-name emr-containers

2023-12-15 17:33:00 [ℹ]  created "emr-testing:Role.rbac.authorization.k8s.io/emr-containers"
2023-12-15 17:33:00 [ℹ]  replaced "emr-testing:RoleBinding.rbac.authorization.k8s.io/emr-containers"
```

Step 2: Start the Job via StartJobRun API
```
POST
https://emr-containers.us-west-2.amazonaws.com/virtualclusters/XXXXXXXXXX/jobruns

{
	"name": "spark-pi-v1",
	"clientToken": "{{$guid}}",
	"executionRoleArn": "<iam-role>",
	"releaseLabel": "emr-6.12.0-latest",
	"jobDriver": {
		"sparkSubmitJobDriver": {
            "entryPoint": "local:///usr/lib/spark/examples/jars/spark-examples.jar",
			"entryPointArguments": ["10"],
            "sparkSubmitParameters": "--class org.apache.spark.examples.SparkPi"
		}
	}
}
```

Step 3: Look for the logs of the Spark Driver.
```
 kubectl logs spark-XXXXXXXXXX-driver -c spark-kubernetes-driver -f
```

**Logs**
Full StackTrace of the exception in the Spark Driver Log.
```
23/12/16 00:10:50 ERROR Utils: Uncaught exception in thread main
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: https://kubernetes.default.svc/api/v1/namespaces/XXXXXXXXXX/persistentvolumeclaims?labelSelector=spark-app-selector%3Dspark-XXXXXXXXXX. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. persistentvolumeclaims is forbidden: User "system:serviceaccount:XXXXXXX:emr-containers-sa-spark-driver-XXXXXXXXXX-XXXXXXXXXX" cannot deletecollection resource "persistentvolumeclaims" in API group "" in the namespace "XXXXXXXXXX".
	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238) ~[kubernetes-client-api-6.4.1.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:538) ~[kubernetes-client-6.4.1.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:558) ~[kubernetes-client-6.4.1.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleDelete(OperationSupport.java:329) ~[kubernetes-client-6.4.1.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.deleteAll(BaseOperation.java:511) ~[kubernetes-client-6.4.1.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.delete(BaseOperation.java:476) ~[kubernetes-client-6.4.1.jar:?]
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend.$anonfun$stop$6(KubernetesClusterSchedulerBackend.scala:196) ~[spark-kubernetes_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1510) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend.stop(KubernetesClusterSchedulerBackend.scala:197) ~[spark-kubernetes_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.SchedulerBackend.stop(SchedulerBackend.scala:33) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.SchedulerBackend.stop$(SchedulerBackend.scala:33) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend.stop(CoarseGrainedSchedulerBackend.scala:53) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.TaskSchedulerImpl.$anonfun$stop$2(TaskSchedulerImpl.scala:989) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1510) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.TaskSchedulerImpl.stop(TaskSchedulerImpl.scala:989) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$stop$4(DAGScheduler.scala:3094) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1510) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:3094) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.SparkContext.$anonfun$stop$12(SparkContext.scala:2129) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1510) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.SparkContext.stop(SparkContext.scala:2129) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.SparkContext.stop(SparkContext.scala:2082) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.sql.SparkSession.stop(SparkSession.scala:763) ~[spark-sql_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.examples.SparkPi$.main(SparkPi.scala:40) ~[spark-examples.jar:3.4.0-amzn-0]
	at org.apache.spark.examples.SparkPi.main(SparkPi.scala) ~[spark-examples.jar:3.4.0-amzn-0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1066) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1158) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1167) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
```

**Anything else we need to know?**
- This is due to the "emr-containers" K8 role not having the permission 
```
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - deletecollection
```

- This behaviour happpens for all versions >= emr-6.12.0 

**Versions**
```
% eksctl info
eksctl version: 0.136.0
kubectl version: v1.27.2
OS: darwin
```

**Comment by TinoSM** [comment]
Same here with ``` cannot deletecollection resource \"services\" in API group \"\" in the namespace \````

I had the same cleanup issues last months with a EMR-containers cluster, we are focusing in something else so didn't have time to fully debug it.
