### ISSUE TITLE
[Bug] SIGSEGV when trying to clean up a deleted eks cluster

### ISSUE THREAD

**Issue by gilbahat** [eksctl-io/eksctl#7450]
### What were you trying to accomplish?
SIGSEGV trying to clean up deleted cluster

### What happened?
✗ eksctl delete cluster --region us-east-1 --force --name ci-3-graybeard-jarring                                      <aws:dev.AdministratorAccess>
I0104 11:10:46.750730   67272 featureflag.go:160] FeatureFlag "Spotinst"=true
I0104 11:10:46.750894   67272 featureflag.go:160] FeatureFlag "SpotinstOcean"=true
I0104 11:10:46.750901   67272 featureflag.go:160] FeatureFlag "SpotinstHybrid"=true
2024-01-04 11:10:49 [!]  failed to create provider for cluster; force = true skipping: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: 6e63d05c-6a5f-442a-931b-1debe2089bc9, ResourceNotFoundException: No cluster found for name: ci-3-graybeard-jarring.
2024-01-04 11:10:50 [ℹ]  deleting EKS cluster "ci-3-graybeard-jarring"
2024-01-04 11:10:52 [!]  stack's status of nodegroup named eksctl-ci-3-graybeard-jarring-cluster is DELETE_FAILED
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5042d9b]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/cluster.(*OwnedCluster).Delete(0xc000c72280, {0x6e40390?, 0x95c26a0}, 0xc000ad7500?, 0x6362420?, 0x80?, 0x1, 0x79?, 0x0?)
	/private/tmp/eksctl-20231128-4712-d4i5gl/pkg/actions/cluster/owned.go:131 +0x75b
github.com/weaveworks/eksctl/pkg/ctl/delete.doDeleteCluster(0xc00020d2c0, 0x1, 0x0?, 0x0?, 0x0?)
	/private/tmp/eksctl-20231128-4712-d4i5gl/pkg/ctl/delete/cluster.go:95 +0x2c2
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterCmd.func1(0xc000024730?, 0x0?, 0x0?, 0x0?, 0x0?)
	/private/tmp/eksctl-20231128-4712-d4i5gl/pkg/ctl/delete/cluster.go:20 +0x13
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterWithRunFunc.func1(0xc00096fc00?, {0xc000024730?, 0x4?, 0x63b669b?})
	/private/tmp/eksctl-20231128-4712-d4i5gl/pkg/ctl/delete/cluster.go:38 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc000978300, {0xc0000246e0, 0x5, 0x5})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005800)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/private/tmp/eksctl-20231128-4712-d4i5gl/cmd/eksctl/main.go:102 +0x552

### How to reproduce it?
* generate a cloudformation stack and bring it to delete_failed status
* delete the eks cluster behind it
* try cleaning up the rest with eksctl

**Logs**
✗ eksctl delete cluster --region us-east-1 --force --name ci-3-graybeard-jarring -v 4                                 <aws:dev.AdministratorAccess>
2024-01-04 11:12:54 [▶]  Setting credentials expiry window to 30 minutes
2024-01-04 11:12:55 [▶]  role ARN for the current session is "REDACTED"
2024-01-04 11:12:56 [!]  failed to create provider for cluster; force = true skipping: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: c91af533-9fdc-45fb-b1b8-6dc4cc8e0b47, ResourceNotFoundException: No cluster found for name: ci-3-graybeard-jarring.
2024-01-04 11:12:56 [▶]  Setting credentials expiry window to 30 minutes
2024-01-04 11:12:57 [▶]  role ARN for the current session is "REDACTED"
2024-01-04 11:12:57 [ℹ]  deleting EKS cluster "ci-3-graybeard-jarring"
2024-01-04 11:12:57 [▶]  cfg.json = \
{
    "kind": "ClusterConfig",
    "apiVersion": "eksctl.io/v1alpha5",
    "metadata": {
        "name": "ci-3-graybeard-jarring",
        "region": "us-east-1",
        "version": "1.27"
    },
    "kubernetesNetworkConfig": {
        "ipFamily": "IPv4"
    },
    "iam": {
        "withOIDC": false,
        "vpcResourceControllerPolicy": true
    },
    "vpc": {
        "cidr": "192.168.0.0/16",
        "manageSharedNodeSecurityGroupRules": true,
        "autoAllocateIPv6": false,
        "nat": {
            "gateway": "Single"
        }
    },
    "privateCluster": {
        "enabled": false,
        "skipEndpointCreation": false
    },
    "cloudWatch": {
        "clusterLogging": {}
    }
}

2024-01-04 11:12:59 [▶]  cluster "ci-3-graybeard-jarring" was created by eksctl
2024-01-04 11:12:59 [▶]  failed to check if cluster is operable: cluster info not available
2024-01-04 11:12:59 [!]  stack's status of nodegroup named eksctl-ci-3-graybeard-jarring-cluster is DELETE_FAILED
2024-01-04 11:12:59 [▶]  nodegroups = []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5042d9b]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/cluster.(*OwnedCluster).Delete(0xc000921640, {0x6e40390?, 0x95c26a0}, 0xc000a7dc80?, 0x6362420?, 0x0?, 0x1, 0x96?, 0x0?)
	/private/tmp/eksctl-20231128-4712-d4i5gl/pkg/actions/cluster/owned.go:131 +0x75b
github.com/weaveworks/eksctl/pkg/ctl/delete.doDeleteCluster(0xc0007a32c0, 0x1, 0x0?, 0x0?, 0x0?)
	/private/tmp/eksctl-20231128-4712-d4i5gl/pkg/ctl/delete/cluster.go:95 +0x2c2
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterCmd.func1(0xc0004c49a0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/private/tmp/eksctl-20231128-4712-d4i5gl/pkg/ctl/delete/cluster.go:20 +0x13
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterWithRunFunc.func1(0xc00096fc00?, {0xc0004c49a0?, 0x4?, 0x63b669b?})
	/private/tmp/eksctl-20231128-4712-d4i5gl/pkg/ctl/delete/cluster.go:38 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc000978300, {0xc0004c48c0, 0x7, 0x7})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000824000)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/private/tmp/eksctl-20231128-4712-d4i5gl/cmd/eksctl/main.go:102 +0x552

**Anything else we need to know?**
MacOS sonoma latest

**Versions**
eksctl version: 0.165.0-dev+2064e6b32.2023-11-28T18:11:10Z
kubectl version: v1.28.4
OS: darwin

**Comment by veekaly** [comment]
Hey @TiberiuGC
I was able to reproduce the issue. The issue is with empty `c.ctl.Status.ClusterInfo` variable in `NewTasksToDeleteClusterWithNodeGroups` function - https://github.com/eksctl-io/eksctl/blob/main/pkg/actions/cluster/owned.go#L127C194-L127C226

I can work on the fix.

**Comment by git4example** [comment]
This is still an issue with latest version 0.199.0 of the eksctl. It was not an issue with 0.188.0. 

As we can see it was reporting cluster dos not exist and gracefully exited. 
```
❯ eksctl delete cluster --name $CLUSTER_NAME --region us-east-2 --disable-nodegroup-eviction --force
2024-12-31 08:49:58 [!]  failed to create provider for cluster; force = true skipping: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: 0de5e175-f5fe-4f65-b811-73c8fc04be94, ResourceNotFoundException: No cluster found for name: FSx-eks-cluster02.
2024-12-31 08:49:59 [ℹ]  deleting EKS cluster "FSx-eks-cluster02"
Error: cluster "FSx-eks-cluster02" does not exist
❯ eksctl version
0.188.0-dev+65f8193d0.2024-07-31T21:39:58Z
```

However, Once I upgrade to 0.199.0 it panic with SIGSEGV error : 

```
❯ eksctl version
0.199.0-dev+228a27121.2024-12-13T23:02:44Z
❯ eksctl delete cluster --name $CLUSTER_NAME --region us-east-2 --disable-nodegroup-eviction --force
2024-12-31 08:52:03 [!]  failed to create provider for cluster; force = true skipping: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: b2c6c572-672d-4294-bb8d-c992f7318f4d, ResourceNotFoundException: No cluster found for name: FSx-eks-cluster02.
2024-12-31 08:52:04 [ℹ]  deleting EKS cluster "FSx-eks-cluster02"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x106b83934]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/cluster.New({0x10899f868, 0x10b444d20}, 0x140006c5760, 0x14000abd830)
	/private/tmp/eksctl-20241213-5247-jr6m1p/pkg/actions/cluster/cluster.go:40 +0x104
github.com/weaveworks/eksctl/pkg/ctl/delete.doDeleteCluster(0x140009bab40, 0x1, 0x1, 0x2540be400, 0x1)
	/private/tmp/eksctl-20241213-5247-jr6m1p/pkg/ctl/delete/cluster.go:88 +0x228
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterCmd.func1(0x14000a24ba0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/private/tmp/eksctl-20241213-5247-jr6m1p/pkg/ctl/delete/cluster.go:20 +0x1c
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterWithRunFunc.func1(0x140009cd400?, {0x14000a24ba0?, 0x4?, 0x106bb7240?})
	/private/tmp/eksctl-20241213-5247-jr6m1p/pkg/ctl/delete/cluster.go:38 +0xb8
github.com/spf13/cobra.(*Command).execute(0x140009d0008, {0x14000a24b40, 0x6, 0x6})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x14000820608)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/private/tmp/eksctl-20241213-5247-jr6m1p/cmd/eksctl/main.go:102 +0x4c0
````
