### ISSUE TITLE
[Bug]  SIGSEGV when creating a cluster with custom AMI

### ISSUE THREAD

**Issue by orsenthil** [eksctl-io/eksctl#7882]
### What were you trying to accomplish?

Create a cluster with custom AMI

### How to reproduce it?

Created an yaml like this

```
$ cat test-cluster.yaml
# An example of ClusterConfig object with ipFamily set to ipv6:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: senthilx-july9-cluster-6
  region: us-west-1
  version: "1.29"

kubernetesNetworkConfig:
  ipFamily: IPv6

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true

managedNodeGroups:
  - amiFamily: AmazonLinux2023
    ami: ami-06780da4f9e123591
    name: mng-1
```

And tried to create a cluster

```
./eksctl create cluster -f test-cluster.yaml
```

And cluster create crashes in this step.

```
2024-07-10 09:37:05 [ℹ]  creating addon
2024-07-10 09:37:06 [ℹ]  successfully created addon
2024-07-10 09:39:08 [ℹ]  deploying stack "eksctl-senthilx-july9-cluster-6-addon-vpc-cni"
2024-07-10 09:39:08 [ℹ]  waiting for CloudFormation stack "eksctl-senthilx-july9-cluster-6-addon-vpc-cni"
2024-07-10 09:39:38 [ℹ]  waiting for CloudFormation stack "eksctl-senthilx-july9-cluster-6-addon-vpc-cni"
2024-07-10 09:40:24 [ℹ]  waiting for CloudFormation stack "eksctl-senthilx-july9-cluster-6-addon-vpc-cni"
2024-07-10 09:40:24 [ℹ]  updating addon
2024-07-10 09:40:35 [ℹ]  addon "vpc-cni" active
2024-07-10 09:40:35 [ℹ]  building managed nodegroup stack "eksctl-senthilx-july9-cluster-6-nodegroup-mng-1"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x63f0f2c]

goroutine 269 [running]:
github.com/weaveworks/eksctl/pkg/nodebootstrap.(*AL2023).createNodeConfig(0xc000995d50)
	/Users/senthilx/git/eksctl/pkg/nodebootstrap/al2023.go:114 +0x52c
github.com/weaveworks/eksctl/pkg/nodebootstrap.(*AL2023).UserData(0xc000995d50)
	/Users/senthilx/git/eksctl/pkg/nodebootstrap/al2023.go:57 +0x1f
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ManagedNodeGroupResourceSet).makeLaunchTemplateData(0xc000b1d860, {0x8e9c498, 0xb895f20})
	/Users/senthilx/git/eksctl/pkg/cfn/builder/managed_launch_template.go:39 +0x398
github.com/weaveworks/eksctl/pkg/cfn/builder.(*ManagedNodeGroupResourceSet).AddAllResources(0xc000b1d860, {0x8e9c498, 0xb895f20})
	/Users/senthilx/git/eksctl/pkg/cfn/builder/managed_nodegroup.go:164 +0x10a5
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).createManagedNodeGroupTask(0xc000ae4420, {0x8e9c498, 0xb895f20}, 0xc0000ddec0, 0xc00016cbd0, 0x0, {0x8ea70b0, 0xc000cb4310})
	/Users/senthilx/git/eksctl/pkg/cfn/manager/nodegroup.go:193 +0x650
github.com/weaveworks/eksctl/pkg/cfn/manager.(*managedNodeGroupTask).Do(0x6e79cc4?, 0x0?)
	/Users/senthilx/git/eksctl/pkg/cfn/manager/tasks.go:41 +0x39
github.com/weaveworks/eksctl/pkg/utils/tasks.doSingleTask(0xc0000dde60, {0x8e4eb28, 0xc00099ee60})
	/Users/senthilx/git/eksctl/pkg/utils/tasks/tasks.go:192 +0xce
github.com/weaveworks/eksctl/pkg/utils/tasks.doSequentialTasks(0xc0000dde60, {0xc000cb4340, 0x1, 0x0?})
	/Users/senthilx/git/eksctl/pkg/utils/tasks/tasks.go:222 +0x68
created by github.com/weaveworks/eksctl/pkg/utils/tasks.(*TaskTree).Do in goroutine 268
	/Users/senthilx/git/eksctl/pkg/utils/tasks/tasks.go:152 +0x179
```

**Versions**

```
$ eksctl info
```

```
$ ./eksctl info
eksctl version: 0.186.0-dev+fdf8ee9b0.2024-07-09T15:38:34Z
kubectl version: v1.29.1
OS: darwin
```

**Comment by cPu1** [comment]
Thanks for the detailed issue. This is an issue with IPv6 support in AL2023. If you retry the command with `ipFamily: IPv4`, it should work. We'll work on a fix soon.
